name: 'Jekyll Actions'
description: 'A GitHub Action to build and publish Jekyll sites to GitHub Pages'
inputs:
  jekyll_src:  
    description: 'The Jekyll website source directory'
    required: false
  gem_src:
    description: 'The Jekyll Gemfile directory'
    required: false
  target_branch:
    description: 'The target branch name the sources get pushed to'
    required: false
  build_only:
    description: 'Will build the Jekyll site without publishing it'
    required: false
  no_lockfile:
    description: 'Set to true if Gemfile.lock is not checked into the repository'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book'
  color: 'blue'
