name: Testing the GitHub Pages publication

on:
  push
    
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-\
    - name: Run with jekyll_src
      uses: ./
      with: 
        jekyll_src: sample_site
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        JEKYLL_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
    - name: Run with jekyll_src and gem_src
      uses: ./
      with: 
        jekyll_src: sample_site
        gem_src: sample_site_gemfiles
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
    - name: Run with target_branch
      uses: ./
      with: 
        target_branch: my_gh_pages_branch
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
    - name: Basic run
      uses: ./
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
